# Generated by Django 2.2.4 on 2019-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190914_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='P'),
            preserve_default=False,
        ),
    ]
