# Generated by Django 2.2.4 on 2019-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
